/**
 * What the golf board accepts, and everything it refuses.
 *
 * The honest framing first, because it decides how much of this is worth
 * building: **this board is client-reported.** The simulation is pure and
 * deterministic, so a server given the same inputs would reach the same state
 * — but `GolfShotV1` records what each shot *did* (where it finished, what it
 * cost), not the power, contact and aim that produced it. There is nothing to
 * replay. A run cannot be recomputed from what is submitted, and so nothing
 * here may be called a verified score.
 *
 * What the checks below are for is narrower and still worth having: they keep
 * the board free of runs that are impossible under the rules the board claims
 * to rank, so a row is at least internally consistent with the hole it says it
 * was played on. That includes the one genuine cross-check available — a shot
 * log, when present, must agree with the totals it is supposed to explain.
 */

import {
  GOLF_COURSE,
  type GolfCourse,
} from "@/lib/game/minigames/golf-course";
import {
  isGolfRunResultV1,
  type GolfRunResultV1,
} from "@/lib/game/minigames/golf-result";
import {
  checkNickname,
  displayNameFor,
} from "@/lib/sportsgang-board/nickname";

/** Largest submission body the route will read, in bytes. */
export const MAX_SUBMISSION_BYTES = 8_192;

/** A run, plus the two things the client adds that the run itself has not got. */
export interface GolfSubmission {
  readonly run: GolfRunResultV1;
  /**
   * The submitting device's anonymous id. Opaque to the server, never shown,
   * and the only thing a board entry is keyed by.
   */
  readonly anonId: string;
  /** What the visitor agreed to be shown as, or absent for `GUEST`. */
  readonly displayName?: string | null;
}

/**
 * An anonymous id, as generated by `crypto.randomUUID()` on the client.
 *
 * Pinned to the UUID shape rather than "any string" so the id cannot be used
 * to smuggle a payload, and so one device cannot claim an id long enough to
 * matter for storage. It is not a secret and not an account.
 */
const ANON_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/** A run id, same shape and same reasoning. */
const RUN_ID = ANON_ID;

export type RejectionCode =
  | "BODY_TOO_LARGE"
  | "MALFORMED_JSON"
  | "NOT_A_RUN"
  | "BAD_ANON_ID"
  | "BAD_RUN_ID"
  | "BAD_NICKNAME"
  | "UNKNOWN_COURSE"
  | "UNKNOWN_RULES"
  | "NOT_COMPLETED"
  | "IMPLAUSIBLE_STROKES"
  | "IMPLAUSIBLE_TIME"
  | "IMPLAUSIBLE_DISTANCE"
  | "SHOT_LOG_DISAGREES";

export type Validated =
  | { readonly ok: true; readonly value: AcceptedSubmission }
  | { readonly ok: false; readonly code: RejectionCode; readonly detail: string };

/** A submission that passed every check, normalised and ready to store. */
export interface AcceptedSubmission {
  readonly runId: string;
  readonly anonId: string;
  readonly courseId: string;
  readonly rulesVersion: string;
  readonly totalStrokes: number;
  readonly shotCount: number;
  readonly penaltyStrokes: number;
  readonly elapsedSimulationMs: number;
  readonly longestDriveM: number;
  readonly displayName: string;
}

function reject(code: RejectionCode, detail: string): Validated {
  return { ok: false, code, detail };
}

/**
 * The longest a single hole may plausibly have taken, in simulated ms.
 *
 * Eight shots, each with its aim, power, contact, flight and roll, plus the
 * dwell between them. An hour is far past generous; the point is to refuse a
 * number that is not a duration at all rather than to police pace of play.
 */
const MAX_ELAPSED_MS = 60 * 60 * 1_000;

/**
 * Checks one submission against the rules the board ranks by.
 *
 * Order matters: the cheap structural checks run before anything that looks at
 * the course, so a malformed body never reaches the parts that assume shape.
 */
export function validateSubmission(
  body: unknown,
  course: GolfCourse = GOLF_COURSE,
): Validated {
  if (typeof body !== "object" || body === null) {
    return reject("MALFORMED_JSON", "the body is not an object");
  }

  const { run, anonId, displayName } = body as Partial<GolfSubmission>;

  if (typeof anonId !== "string" || !ANON_ID.test(anonId)) {
    return reject("BAD_ANON_ID", "anonId is not a uuid");
  }

  // The foundation's own validator, reused rather than reimplemented: it is
  // what defines a v1 run, including that totalStrokes is the derived sum.
  if (!isGolfRunResultV1(run)) {
    return reject("NOT_A_RUN", "the run is not a valid GolfRunResultV1");
  }

  if (!RUN_ID.test(run.runId)) {
    return reject("BAD_RUN_ID", "runId is not a uuid");
  }

  // Absent and null both mean "no name given", which is GUEST. Only a name
  // that was actually offered and cannot be used is an error.
  if (displayName !== undefined && displayName !== null) {
    if (typeof displayName !== "string") {
      return reject("BAD_NICKNAME", "displayName is not a string");
    }
    if (!checkNickname(displayName).ok) {
      return reject("BAD_NICKNAME", "displayName is empty or too long");
    }
  }

  // A board that mixes rule sets is not a board. Both halves of the key are
  // checked against the course this deployment actually ships.
  if (run.courseId !== course.courseId) {
    return reject("UNKNOWN_COURSE", `unknown courseId ${run.courseId}`);
  }
  if (run.rulesVersion !== course.rulesVersion) {
    return reject("UNKNOWN_RULES", `unknown rulesVersion ${run.rulesVersion}`);
  }

  // Only a finished hole is ranked. An abandoned run is a fact worth keeping
  // locally, but it has no score, and admitting one at zero strokes would put
  // a player who gave up at the top of the board.
  if (run.status !== "completed") {
    return reject("NOT_COMPLETED", "only a completed hole can be ranked");
  }

  if (
    !Number.isInteger(run.shotCount) ||
    run.shotCount < 1 ||
    run.shotCount > course.maxShots
  ) {
    return reject(
      "IMPLAUSIBLE_STROKES",
      `shotCount ${run.shotCount} outside 1..${course.maxShots}`,
    );
  }
  if (
    !Number.isInteger(run.penaltyStrokes) ||
    run.penaltyStrokes < 0 ||
    run.penaltyStrokes > course.maxShots
  ) {
    return reject(
      "IMPLAUSIBLE_STROKES",
      `penaltyStrokes ${run.penaltyStrokes} outside 0..${course.maxShots}`,
    );
  }
  // isGolfRunResultV1 already re-derives this; asserted again here so the
  // board's own rule does not depend on a check living in another module.
  if (run.totalStrokes !== run.shotCount + run.penaltyStrokes) {
    return reject("IMPLAUSIBLE_STROKES", "totalStrokes is not the sum");
  }

  if (
    !Number.isFinite(run.elapsedSimulationMs) ||
    run.elapsedSimulationMs <= 0 ||
    run.elapsedSimulationMs > MAX_ELAPSED_MS
  ) {
    return reject("IMPLAUSIBLE_TIME", "elapsedSimulationMs is not a duration");
  }

  // A completed hole finished in the cup, so nothing is left to travel.
  if (!Number.isFinite(run.remainingDistanceM) || run.remainingDistanceM > 1) {
    return reject(
      "IMPLAUSIBLE_DISTANCE",
      "a completed hole cannot have distance remaining",
    );
  }

  // Nothing can be driven further than the hole is long plus the width of the
  // out-of-bounds margin behind it.
  const longestPossible = course.holeM + course.beyondGreenLimitM;
  if (
    !Number.isFinite(run.longestDriveM) ||
    run.longestDriveM < 0 ||
    run.longestDriveM > longestPossible
  ) {
    return reject(
      "IMPLAUSIBLE_DISTANCE",
      `longestDriveM ${run.longestDriveM} outside 0..${longestPossible}`,
    );
  }

  // The one real cross-check available: if the client sent the log, it has to
  // explain the totals it was sent with. This does not make the run verified —
  // the log records outcomes, not the inputs that caused them — but a total
  // that its own log contradicts is refused rather than ranked.
  if (run.shotLog !== undefined) {
    if (run.shotLog.length !== run.shotCount) {
      return reject(
        "SHOT_LOG_DISAGREES",
        `shotLog has ${run.shotLog.length} shots, shotCount says ${run.shotCount}`,
      );
    }
    const penalties = run.shotLog.reduce((sum, shot) => sum + shot.penalty, 0);
    if (penalties !== run.penaltyStrokes) {
      return reject(
        "SHOT_LOG_DISAGREES",
        `shotLog penalties total ${penalties}, run says ${run.penaltyStrokes}`,
      );
    }
    for (const shot of run.shotLog) {
      if (shot.atSimulationMs > run.elapsedSimulationMs) {
        return reject("SHOT_LOG_DISAGREES", "a shot is played after the run ended");
      }
    }
  }

  return {
    ok: true,
    value: {
      runId: run.runId,
      anonId,
      courseId: run.courseId,
      rulesVersion: run.rulesVersion,
      totalStrokes: run.totalStrokes,
      shotCount: run.shotCount,
      penaltyStrokes: run.penaltyStrokes,
      elapsedSimulationMs: run.elapsedSimulationMs,
      longestDriveM: run.longestDriveM,
      // Normalised on the server too. What a visitor agreed to publish and
      // what appears on the board have to be the same string.
      displayName: displayNameFor(displayName),
    },
  };
}

/** HTTP status for each refusal. Everything here is the client's fault. */
export function statusForRejection(code: RejectionCode): number {
  return code === "BODY_TOO_LARGE" ? 413 : 400;
}
